// path: proto/price/v1/price.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: price/v1/price.proto

package pricev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                            // e.g., "BTCUSDT"
	IntervalMs    int64                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // e.g., 1000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_price_v1_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_v1_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_price_v1_price_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubscribeRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	WindowStartMs int64                  `protobuf:"varint,2,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"`
	WindowEndMs   int64                  `protobuf:"varint,3,opt,name=window_end_ms,json=windowEndMs,proto3" json:"window_end_ms,omitempty"`
	Open          float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,8,opt,name=volume,proto3" json:"volume,omitempty"`
	Vwap          float64                `protobuf:"fixed64,9,opt,name=vwap,proto3" json:"vwap,omitempty"`
	IsFinal       bool                   `protobuf:"varint,10,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Exchange      string                 `protobuf:"bytes,11,opt,name=exchange,proto3" json:"exchange,omitempty"`
	LastTradeTs   int64                  `protobuf:"varint,12,opt,name=last_trade_ts,json=lastTradeTs,proto3" json:"last_trade_ts,omitempty"`
	TradeCount    uint64                 `protobuf:"varint,13,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_price_v1_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_price_v1_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_price_v1_price_proto_rawDescGZIP(), []int{1}
}

func (x *Candle) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Candle) GetWindowStartMs() int64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

func (x *Candle) GetWindowEndMs() int64 {
	if x != nil {
		return x.WindowEndMs
	}
	return 0
}

func (x *Candle) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Candle) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Candle) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Candle) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Candle) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Candle) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

func (x *Candle) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *Candle) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Candle) GetLastTradeTs() int64 {
	if x != nil {
		return x.LastTradeTs
	}
	return 0
}

func (x *Candle) GetTradeCount() uint64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

var File_price_v1_price_proto protoreflect.FileDescriptor

const file_price_v1_price_proto_rawDesc = "" +
	"\n" +
	"\x14price/v1/price.proto\x12\bprice.v1\"K\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x03R\n" +
	"intervalMs\"\xe4\x02\n" +
	"\x06Candle\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12&\n" +
	"\x0fwindow_start_ms\x18\x02 \x01(\x03R\rwindowStartMs\x12\"\n" +
	"\rwindow_end_ms\x18\x03 \x01(\x03R\vwindowEndMs\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\b \x01(\x01R\x06volume\x12\x12\n" +
	"\x04vwap\x18\t \x01(\x01R\x04vwap\x12\x19\n" +
	"\bis_final\x18\n" +
	" \x01(\bR\aisFinal\x12\x1a\n" +
	"\bexchange\x18\v \x01(\tR\bexchange\x12\"\n" +
	"\rlast_trade_ts\x18\f \x01(\x03R\vlastTradeTs\x12\x1f\n" +
	"\vtrade_count\x18\r \x01(\x04R\n" +
	"tradeCount2S\n" +
	"\vPriceStream\x12D\n" +
	"\x10StreamAggregates\x12\x1a.price.v1.SubscribeRequest\x1a\x10.price.v1.Candle\"\x000\x01B?Z=github.com/binaridigital/price-engine/proto/price/v1;pricev1b\x06proto3"

var (
	file_price_v1_price_proto_rawDescOnce sync.Once
	file_price_v1_price_proto_rawDescData []byte
)

func file_price_v1_price_proto_rawDescGZIP() []byte {
	file_price_v1_price_proto_rawDescOnce.Do(func() {
		file_price_v1_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_price_v1_price_proto_rawDesc), len(file_price_v1_price_proto_rawDesc)))
	})
	return file_price_v1_price_proto_rawDescData
}

var file_price_v1_price_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_price_v1_price_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: price.v1.SubscribeRequest
	(*Candle)(nil),           // 1: price.v1.Candle
}
var file_price_v1_price_proto_depIdxs = []int32{
	0, // 0: price.v1.PriceStream.StreamAggregates:input_type -> price.v1.SubscribeRequest
	1, // 1: price.v1.PriceStream.StreamAggregates:output_type -> price.v1.Candle
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_price_v1_price_proto_init() }
func file_price_v1_price_proto_init() {
	if File_price_v1_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_price_v1_price_proto_rawDesc), len(file_price_v1_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_price_v1_price_proto_goTypes,
		DependencyIndexes: file_price_v1_price_proto_depIdxs,
		MessageInfos:      file_price_v1_price_proto_msgTypes,
	}.Build()
	File_price_v1_price_proto = out.File
	file_price_v1_price_proto_goTypes = nil
	file_price_v1_price_proto_depIdxs = nil
}
