// path: proto/price/v1/price.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: price/v1/price.proto

package pricev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PriceStream_StreamAggregates_FullMethodName = "/price.v1.PriceStream/StreamAggregates"
)

// PriceStreamClient is the client API for PriceStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceStreamClient interface {
	StreamAggregates(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Candle], error)
}

type priceStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceStreamClient(cc grpc.ClientConnInterface) PriceStreamClient {
	return &priceStreamClient{cc}
}

func (c *priceStreamClient) StreamAggregates(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Candle], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceStream_ServiceDesc.Streams[0], PriceStream_StreamAggregates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Candle]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceStream_StreamAggregatesClient = grpc.ServerStreamingClient[Candle]

// PriceStreamServer is the server API for PriceStream service.
// All implementations must embed UnimplementedPriceStreamServer
// for forward compatibility.
type PriceStreamServer interface {
	StreamAggregates(*SubscribeRequest, grpc.ServerStreamingServer[Candle]) error
	mustEmbedUnimplementedPriceStreamServer()
}

// UnimplementedPriceStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriceStreamServer struct{}

func (UnimplementedPriceStreamServer) StreamAggregates(*SubscribeRequest, grpc.ServerStreamingServer[Candle]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAggregates not implemented")
}
func (UnimplementedPriceStreamServer) mustEmbedUnimplementedPriceStreamServer() {}
func (UnimplementedPriceStreamServer) testEmbeddedByValue()                     {}

// UnsafePriceStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceStreamServer will
// result in compilation errors.
type UnsafePriceStreamServer interface {
	mustEmbedUnimplementedPriceStreamServer()
}

func RegisterPriceStreamServer(s grpc.ServiceRegistrar, srv PriceStreamServer) {
	// If the following call pancis, it indicates UnimplementedPriceStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriceStream_ServiceDesc, srv)
}

func _PriceStream_StreamAggregates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceStreamServer).StreamAggregates(m, &grpc.GenericServerStream[SubscribeRequest, Candle]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceStream_StreamAggregatesServer = grpc.ServerStreamingServer[Candle]

// PriceStream_ServiceDesc is the grpc.ServiceDesc for PriceStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "price.v1.PriceStream",
	HandlerType: (*PriceStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAggregates",
			Handler:       _PriceStream_StreamAggregates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "price/v1/price.proto",
}
