// path: proto/price/v1/price.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: price/v1/price.proto

package pricev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstrumentType int32

const (
	InstrumentType_IT_UNSPECIFIED InstrumentType = 0
	InstrumentType_IT_CRYPTO_SPOT InstrumentType = 1
	InstrumentType_IT_FX_SPOT     InstrumentType = 2
)

// Enum value maps for InstrumentType.
var (
	InstrumentType_name = map[int32]string{
		0: "IT_UNSPECIFIED",
		1: "IT_CRYPTO_SPOT",
		2: "IT_FX_SPOT",
	}
	InstrumentType_value = map[string]int32{
		"IT_UNSPECIFIED": 0,
		"IT_CRYPTO_SPOT": 1,
		"IT_FX_SPOT":     2,
	}
)

func (x InstrumentType) Enum() *InstrumentType {
	p := new(InstrumentType)
	*p = x
	return p
}

func (x InstrumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstrumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_price_v1_price_proto_enumTypes[0].Descriptor()
}

func (InstrumentType) Type() protoreflect.EnumType {
	return &file_price_v1_price_proto_enumTypes[0]
}

func (x InstrumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstrumentType.Descriptor instead.
func (InstrumentType) EnumDescriptor() ([]byte, []int) {
	return file_price_v1_price_proto_rawDescGZIP(), []int{0}
}

type PriceType int32

const (
	PriceType_PT_UNSPECIFIED PriceType = 0
	PriceType_PT_TRADE       PriceType = 1 // comes from an executed trade (e.g., crypto)
	PriceType_PT_BID         PriceType = 2
	PriceType_PT_ASK         PriceType = 3
	PriceType_PT_MID         PriceType = 4 // (bid+ask)/2 or provider mid
)

// Enum value maps for PriceType.
var (
	PriceType_name = map[int32]string{
		0: "PT_UNSPECIFIED",
		1: "PT_TRADE",
		2: "PT_BID",
		3: "PT_ASK",
		4: "PT_MID",
	}
	PriceType_value = map[string]int32{
		"PT_UNSPECIFIED": 0,
		"PT_TRADE":       1,
		"PT_BID":         2,
		"PT_ASK":         3,
		"PT_MID":         4,
	}
)

func (x PriceType) Enum() *PriceType {
	p := new(PriceType)
	*p = x
	return p
}

func (x PriceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriceType) Descriptor() protoreflect.EnumDescriptor {
	return file_price_v1_price_proto_enumTypes[1].Descriptor()
}

func (PriceType) Type() protoreflect.EnumType {
	return &file_price_v1_price_proto_enumTypes[1]
}

func (x PriceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriceType.Descriptor instead.
func (PriceType) EnumDescriptor() ([]byte, []int) {
	return file_price_v1_price_proto_rawDescGZIP(), []int{1}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                            // e.g., "BTCUSDT", "EURUSD"
	IntervalMs    int64                  `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // e.g., 1000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_price_v1_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_v1_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_price_v1_price_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubscribeRequest) GetIntervalMs() int64 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	WindowStartMs int64                  `protobuf:"varint,2,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"`
	WindowEndMs   int64                  `protobuf:"varint,3,opt,name=window_end_ms,json=windowEndMs,proto3" json:"window_end_ms,omitempty"`
	Open          float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,8,opt,name=volume,proto3" json:"volume,omitempty"`
	Vwap          float64                `protobuf:"fixed64,9,opt,name=vwap,proto3" json:"vwap,omitempty"`
	IsFinal       bool                   `protobuf:"varint,10,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Exchange      string                 `protobuf:"bytes,11,opt,name=exchange,proto3" json:"exchange,omitempty"`                             // data source/provider
	LastTradeTs   int64                  `protobuf:"varint,12,opt,name=last_trade_ts,json=lastTradeTs,proto3" json:"last_trade_ts,omitempty"` // or last quote ts
	TradeCount    uint64                 `protobuf:"varint,13,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`
	// New fields (ISO/regulator-aligned)
	InstrumentType InstrumentType `protobuf:"varint,14,opt,name=instrument_type,json=instrumentType,proto3,enum=price.v1.InstrumentType" json:"instrument_type,omitempty"`
	PriceType      PriceType      `protobuf:"varint,15,opt,name=price_type,json=priceType,proto3,enum=price.v1.PriceType" json:"price_type,omitempty"`
	BaseCcy        string         `protobuf:"bytes,16,opt,name=base_ccy,json=baseCcy,proto3" json:"base_ccy,omitempty"`    // ISO 4217, e.g., "EUR"
	QuoteCcy       string         `protobuf:"bytes,17,opt,name=quote_ccy,json=quoteCcy,proto3" json:"quote_ccy,omitempty"` // ISO 4217, e.g., "USD"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_price_v1_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_price_v1_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_price_v1_price_proto_rawDescGZIP(), []int{1}
}

func (x *Candle) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Candle) GetWindowStartMs() int64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

func (x *Candle) GetWindowEndMs() int64 {
	if x != nil {
		return x.WindowEndMs
	}
	return 0
}

func (x *Candle) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Candle) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Candle) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Candle) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Candle) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Candle) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

func (x *Candle) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *Candle) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Candle) GetLastTradeTs() int64 {
	if x != nil {
		return x.LastTradeTs
	}
	return 0
}

func (x *Candle) GetTradeCount() uint64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *Candle) GetInstrumentType() InstrumentType {
	if x != nil {
		return x.InstrumentType
	}
	return InstrumentType_IT_UNSPECIFIED
}

func (x *Candle) GetPriceType() PriceType {
	if x != nil {
		return x.PriceType
	}
	return PriceType_PT_UNSPECIFIED
}

func (x *Candle) GetBaseCcy() string {
	if x != nil {
		return x.BaseCcy
	}
	return ""
}

func (x *Candle) GetQuoteCcy() string {
	if x != nil {
		return x.QuoteCcy
	}
	return ""
}

var File_price_v1_price_proto protoreflect.FileDescriptor

const file_price_v1_price_proto_rawDesc = "" +
	"\n" +
	"\x14price/v1/price.proto\x12\bprice.v1\"K\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\x03R\n" +
	"intervalMs\"\x93\x04\n" +
	"\x06Candle\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12&\n" +
	"\x0fwindow_start_ms\x18\x02 \x01(\x03R\rwindowStartMs\x12\"\n" +
	"\rwindow_end_ms\x18\x03 \x01(\x03R\vwindowEndMs\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\b \x01(\x01R\x06volume\x12\x12\n" +
	"\x04vwap\x18\t \x01(\x01R\x04vwap\x12\x19\n" +
	"\bis_final\x18\n" +
	" \x01(\bR\aisFinal\x12\x1a\n" +
	"\bexchange\x18\v \x01(\tR\bexchange\x12\"\n" +
	"\rlast_trade_ts\x18\f \x01(\x03R\vlastTradeTs\x12\x1f\n" +
	"\vtrade_count\x18\r \x01(\x04R\n" +
	"tradeCount\x12A\n" +
	"\x0finstrument_type\x18\x0e \x01(\x0e2\x18.price.v1.InstrumentTypeR\x0einstrumentType\x122\n" +
	"\n" +
	"price_type\x18\x0f \x01(\x0e2\x13.price.v1.PriceTypeR\tpriceType\x12\x19\n" +
	"\bbase_ccy\x18\x10 \x01(\tR\abaseCcy\x12\x1b\n" +
	"\tquote_ccy\x18\x11 \x01(\tR\bquoteCcy*H\n" +
	"\x0eInstrumentType\x12\x12\n" +
	"\x0eIT_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eIT_CRYPTO_SPOT\x10\x01\x12\x0e\n" +
	"\n" +
	"IT_FX_SPOT\x10\x02*Q\n" +
	"\tPriceType\x12\x12\n" +
	"\x0ePT_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bPT_TRADE\x10\x01\x12\n" +
	"\n" +
	"\x06PT_BID\x10\x02\x12\n" +
	"\n" +
	"\x06PT_ASK\x10\x03\x12\n" +
	"\n" +
	"\x06PT_MID\x10\x042Q\n" +
	"\vPriceStream\x12B\n" +
	"\x10StreamAggregates\x12\x1a.price.v1.SubscribeRequest\x1a\x10.price.v1.Candle0\x01B>Z<github.com/binaridigital/price-engine/proto/price/v1;pricev1b\x06proto3"

var (
	file_price_v1_price_proto_rawDescOnce sync.Once
	file_price_v1_price_proto_rawDescData []byte
)

func file_price_v1_price_proto_rawDescGZIP() []byte {
	file_price_v1_price_proto_rawDescOnce.Do(func() {
		file_price_v1_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_price_v1_price_proto_rawDesc), len(file_price_v1_price_proto_rawDesc)))
	})
	return file_price_v1_price_proto_rawDescData
}

var file_price_v1_price_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_price_v1_price_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_price_v1_price_proto_goTypes = []any{
	(InstrumentType)(0),      // 0: price.v1.InstrumentType
	(PriceType)(0),           // 1: price.v1.PriceType
	(*SubscribeRequest)(nil), // 2: price.v1.SubscribeRequest
	(*Candle)(nil),           // 3: price.v1.Candle
}
var file_price_v1_price_proto_depIdxs = []int32{
	0, // 0: price.v1.Candle.instrument_type:type_name -> price.v1.InstrumentType
	1, // 1: price.v1.Candle.price_type:type_name -> price.v1.PriceType
	2, // 2: price.v1.PriceStream.StreamAggregates:input_type -> price.v1.SubscribeRequest
	3, // 3: price.v1.PriceStream.StreamAggregates:output_type -> price.v1.Candle
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_price_v1_price_proto_init() }
func file_price_v1_price_proto_init() {
	if File_price_v1_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_price_v1_price_proto_rawDesc), len(file_price_v1_price_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_price_v1_price_proto_goTypes,
		DependencyIndexes: file_price_v1_price_proto_depIdxs,
		EnumInfos:         file_price_v1_price_proto_enumTypes,
		MessageInfos:      file_price_v1_price_proto_msgTypes,
	}.Build()
	File_price_v1_price_proto = out.File
	file_price_v1_price_proto_goTypes = nil
	file_price_v1_price_proto_depIdxs = nil
}
